### ISSUE TITLE
Criar scripts do banco PostgreSQL

### ISSUE THREAD

**Issue by YuriMaineri** [alrmgs/TrabalhoFinal#1]
Encarregado de fazer: Alexia

**Comment by diasfd** [comment]
Dados do banco:

Versão do servidor: 9.3
Host para conexão: pgsql.homolog.kinghost.net
Host alternativo: pgsql03-farm62.kinghost.net
Porta de conexão PgSQL: 5432
Usuário para conexão: homolog
Nome da base: homolog
Senha do Banco: 8UnFzPbFtsHjLPR
