### ISSUE TITLE
Criação do projeto em Java (front-end)

### ISSUE THREAD

**Issue by YuriMaineri** [alrmgs/TrabalhoFinal#4]
Encarregado: Vittorio

**Comment by diasfd** [comment]
Opa, dados de acesso ao servidor web:

Filezilla: https://filezilla-project.org/download.php

Host FTP: ftp.homolog.kinghost.net
Host FTP alternativo: ftp.web1513.kinghost.net
Usuário FTP: homolog
Senha: DKSJAopDk92081309MDFKLE

Obs: Nas máquinas da faculdade tem que fazer acesso via navegador, porque o Firewall bloqueia os outros tipos de acesso:

Acesso WebFTP: http://webftp.kinghost.net/

**Comment by VittorioBarella** [comment]
[Link para o index do trabalho](https://github.com/VittorioBarella/Trabalho-Engenheria-Software-II-)

**Comment by VittorioBarella** [comment]
[Telas prontas](https://github.com/VittorioBarella/Trabalho-Engenharia-Software-II.git)

**Comment by YuriMaineri** [comment]
Projeto desenvolvido em Java e PHP na parte do back-end, irá ser commitado no git.
